replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/geoserver/geoserver
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

service:
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge

persistence:
  enabled: false

geoserver:
  dataDir: /opt/geoserver/data_dir
  javaOpts: "-Xms512m -Xmx2g"
